// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://stikejzsduzoqtcuexir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0aWtlanpzZHV6b3F0Y3VleGlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNDE3NzEsImV4cCI6MjA2MDgxNzc3MX0.GJ621SDeDUoNO_ByOjfuM__VGLXyBsRcGYJlmzJpupA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);